# Generated by Django 3.2.6 on 2021-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienceindicator',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
        migrations.AlterField(
            model_name='termrankingaccount',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)'),
        ),
        migrations.AlterField(
            model_name='termrankingaccount',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)'),
        ),
        migrations.AlterField(
            model_name='termrankingaccount',
            name='ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위'),
        ),
        migrations.AlterField(
            model_name='termrankingaccount',
            name='ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)'),
        ),
    ]
