# Generated by Django 3.2.6 on 2021-08-25 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210825_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienceindicator',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AddField(
            model_name='audiencequality',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AddField(
            model_name='demographicsgender',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AddField(
            model_name='featuringscore',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AddField(
            model_name='reachscore',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AddField(
            model_name='realinfluencescore',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간'),
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iguserinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tkuserinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ytchannelinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정 시간'),
            preserve_default=False,
        ),
    ]
