# Generated by Django 3.2.6 on 2021-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210825_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='iguserinfo',
            name='json_post',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='iguserinfo',
            name='json_userprofile',
            field=models.JSONField(null=True),
        ),
    ]
