# Generated by Django 3.2.6 on 2021-08-25 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('component', '0001_initial'),
        ('report', '0005_auto_20210825_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienceindicator',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='json_parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터'),
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위')),
                ('ranking_rate', models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)')),
                ('estimate_ranking', models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (전체 풀)')),
                ('estimate_ranking_rate', models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(전체 풀)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='어드민 수정 시간')),
                ('is_force_modify', models.BooleanField(blank=True, default=True, verbose_name='어드민 수정값 고정')),
                ('json_parameter', models.JSONField(blank=True, null=True, verbose_name='계산식 관련 원형 데이터')),
                ('version', models.IntegerField(blank=True, choices=[(0, '도달수 기반 계산'), (1, '기존 피처링 엔진'), (2, '수집된 데이터 기반')], default=-1)),
                ('version_calculate', models.IntegerField(blank=True, default=-1, verbose_name='적용된 계산식 버전')),
                ('crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='계산될때 기준 수집 시간')),
                ('accuracy', models.IntegerField(blank=True, choices=[(0, '매우낮음'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'bool'), (1, 'int'), (2, 'float'), (3, 'char')], default=0)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_boolean_admin', models.BooleanField(blank=True, null=True)),
                ('value_int', models.BigIntegerField(blank=True, null=True)),
                ('value_int_admin', models.BigIntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_float_admin', models.FloatField(blank=True, null=True)),
                ('value_char', models.CharField(blank=True, max_length=1000, null=True)),
                ('value_char_admin', models.FloatField(blank=True, max_length=1000, null=True)),
                ('ig_userinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend', to='report.iguserinfo')),
                ('modifier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trend', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
                ('tags', models.ManyToManyField(blank=True, to='component.Tag')),
                ('tk_userinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend', to='report.tkuserinfo')),
                ('yt_channelinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend', to='report.ytchannelinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
