# Generated by Django 3.2.6 on 2021-08-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20210825_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencequality',
            name='follower_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiencequality',
            name='real_follower_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
