# Generated by Django 3.2.6 on 2021-08-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_demographicslanguages'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienceindicator',
            name='audience_aggressive_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='적극적인 오디언스 비율'),
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='audience_business_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='오디언스 비즈니스 계정 비율'),
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='avg_comment_count',
            field=models.FloatField(blank=True, null=True, verbose_name='평균 댓글 수'),
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='avg_follower_count',
            field=models.FloatField(blank=True, null=True, verbose_name='평균 팔로워 수'),
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='avg_following_count',
            field=models.FloatField(blank=True, null=True, verbose_name='평균 팔로워 수'),
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='avg_like_count',
            field=models.FloatField(blank=True, null=True, verbose_name='평균 좋아요 수'),
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='avg_media_count',
            field=models.FloatField(blank=True, null=True, verbose_name='평균 팔로워 수'),
        ),
    ]
