# Generated by Django 3.2.6 on 2021-08-27 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20210826_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographicslanguages',
            old_name='language_code_count',
            new_name='language_code_counts',
        ),
        migrations.RenameField(
            model_name='demographicslanguages',
            old_name='language_code_rate',
            new_name='language_code_rates',
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='all_age_counts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대(~18), 20대초(18-24), 20대후(25-30), 30대, 40대, 50대이상', null=True, size=5, verbose_name='나이 갯수(갯수 콤마로 구분)'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='all_age_rates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대(~18), 20대초(18-24), 20대후(25-30), 30대, 40대, 50대이상', null=True, size=5, verbose_name='나이 비율(1.0~0.0)'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='man_age_counts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대(~18), 20대초(18-24), 20대후(25-30), 30대, 40대, 50대이상', null=True, size=5, verbose_name='남자 나이 갯수(갯수 콤마로 구분)'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='man_age_rates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대(~18), 20대초(18-24), 20대후(25-30), 30대, 40대, 50대이상', null=True, size=5, verbose_name='남자 나이 비율(1.0~0.0)'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='woman_age_counts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대(~18), 20대초(18-24), 20대후(25-30), 30대, 40대, 50대이상', null=True, size=5, verbose_name='여자 나이 갯수(갯수 콤마로 구분)'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='woman_age_rates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대(~18), 20대초(18-24), 20대후(25-30), 30대, 40대, 50대이상', null=True, size=5, verbose_name='여자 나이 비율(1.0~0.0)'),
        ),
        migrations.AlterUniqueTogether(
            name='audienceindicator',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='audiencequality',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='demographicsage',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='demographicsgender',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='demographicslanguages',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='featuringscore',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='reachscore',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='realinfluencescore',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.AlterUniqueTogether(
            name='trend',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo')},
        ),
        migrations.RemoveField(
            model_name='demographicsage',
            name='all_age_rate',
        ),
        migrations.RemoveField(
            model_name='demographicsage',
            name='man_age_rate',
        ),
        migrations.RemoveField(
            model_name='demographicsage',
            name='woman_age_rate',
        ),
    ]
