# Generated by Django 3.2.6 on 2021-08-27 11:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20210827_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audienceindicator',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='audiencequality',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='demographicsage',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='demographicsgender',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='demographicslanguages',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='engagement',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='featuringscore',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='reachscore',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='realinfluencescore',
            old_name='version',
            new_name='version_type',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='version',
            new_name='version_type',
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='all_age_counts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대, 20대초반, 20대후반, 30대초반, 30대후반, 40대, 50대이상', null=True, size=7, verbose_name='나이 갯수(갯수 콤마로 구분)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='all_age_rates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='10대, 20대초반, 20대후반, 30대초반, 30대후반, 40대, 50대이상', null=True, size=7, verbose_name='나이 비율(1.0~0.0)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='man_age_counts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대, 20대초반, 20대후반, 30대초반, 30대후반, 40대, 50대이상', null=True, size=7, verbose_name='남자 나이 갯수(갯수 콤마로 구분)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='man_age_rates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='10대, 20대초반, 20대후반, 30대초반, 30대후반, 40대, 50대이상', null=True, size=7, verbose_name='남자 나이 비율(1.0~0.0)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='woman_age_counts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='10대, 20대초반, 20대후반, 30대초반, 30대후반, 40대, 50대이상', null=True, size=7, verbose_name='여자 나이 갯수(갯수 콤마로 구분)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='woman_age_rates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='10대, 20대초반, 20대후반, 30대초반, 30대후반, 40대, 50대이상', null=True, size=7, verbose_name='여자 나이 비율(1.0~0.0)'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='demographicslanguages',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='accuracy',
            field=models.IntegerField(blank=True, choices=[(0, '매우낮음 (기본 초기값으로 설정)'), (1, '낮음'), (2, '중간'), (3, '높음'), (4, '매우 높음')], default=-1, verbose_name='정확도'),
        ),
    ]
