# Generated by Django 3.2.6 on 2021-09-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20210827_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audienceindicator',
            options={'verbose_name': '오디언스 지표', 'verbose_name_plural': '오디언스 지표'},
        ),
        migrations.AlterModelOptions(
            name='audiencequality',
            options={'verbose_name': '진짜 팔로워', 'verbose_name_plural': '진짜 팔로워'},
        ),
        migrations.AlterModelOptions(
            name='demographicsage',
            options={'verbose_name': '연령', 'verbose_name_plural': '연령'},
        ),
        migrations.AlterModelOptions(
            name='demographicsgender',
            options={'verbose_name': '성별', 'verbose_name_plural': '성별'},
        ),
        migrations.AlterModelOptions(
            name='demographicslanguages',
            options={'verbose_name': '언어', 'verbose_name_plural': '언어'},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'verbose_name': '진짜 반응률', 'verbose_name_plural': '진짜 반응률'},
        ),
        migrations.AlterModelOptions(
            name='featuringscore',
            options={'verbose_name': '피처링 스코어', 'verbose_name_plural': '피처링 스코어'},
        ),
        migrations.AlterModelOptions(
            name='iguserinfo',
            options={'verbose_name': '인스타그램 계정', 'verbose_name_plural': '인스타그램 계정들'},
        ),
        migrations.AlterModelOptions(
            name='reachscore',
            options={'verbose_name': '도달수', 'verbose_name_plural': '도달수'},
        ),
        migrations.AlterModelOptions(
            name='realinfluencescore',
            options={'verbose_name': '진짜 영향력', 'verbose_name_plural': '진짜 영향력'},
        ),
        migrations.AlterModelOptions(
            name='trend',
            options={'verbose_name': '성장성', 'verbose_name_plural': '성장성'},
        ),
        migrations.RemoveField(
            model_name='iguserinfo',
            name='section_shortcut',
        ),
        migrations.AddField(
            model_name='realinfluencescore',
            name='audience_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.audiencequality', verbose_name='[계산지표] 도달'),
        ),
        migrations.AddField(
            model_name='reportstatistics',
            name='section_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.categorysection'),
        ),
        migrations.AddField(
            model_name='reportstatistics',
            name='section_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.countrysection'),
        ),
        migrations.AddField(
            model_name='reportstatistics',
            name='section_follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.followersection'),
        ),
        migrations.AddField(
            model_name='reportstatistics',
            name='section_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.platformsection'),
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='audienceindicator',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='audiencequality',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='demographicsage',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='demographicsgender',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='demographicslanguages',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='demographicslanguages',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='demographicslanguages',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='featuringscore',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='iguserinfo',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='iguserinfo',
            name='json_post',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iguserinfo',
            name='json_userprofile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='realinfluencescore',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='termrankingaccount',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='termrankingaccount',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='tkuserinfo',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='estimate_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='estimate_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterField(
            model_name='ytchannelinfo',
            name='is_force_modify',
            field=models.BooleanField(blank=True, default=True, help_text='엔진 분석데이터 변화로 변경되지 않도록 값을 고정 합니다.', verbose_name='어드민 수정값 고정하기'),
        ),
        migrations.AlterUniqueTogether(
            name='audienceindicator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='audiencequality',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='demographicsage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='demographicsgender',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='demographicslanguages',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='featuringscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reachscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='realinfluencescore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reportstatistics',
            unique_together={('section_platform', 'section_follower', 'section_category', 'section_country', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='termrankingaccount',
            unique_together={('ig_userinfo', 'tk_userinfo', 'yt_channelinfo', 'define_date')},
        ),
        migrations.AlterUniqueTogether(
            name='trend',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reportstatistics',
            name='shortcut',
        ),
        migrations.RemoveField(
            model_name='termrankingaccount',
            name='section_shortcut',
        ),
        migrations.DeleteModel(
            name='SectionShortcut',
        ),
    ]
