# Generated by Django 3.2.6 on 2021-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20210909_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstatisticsattribute',
            name='value',
            field=models.FloatField(default=0, verbose_name='속성값'),
        ),
    ]
