# Generated by Django 3.2.6 on 2021-09-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_alter_reportstatisticsattribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='termrankingaccount',
            name='section_ranking',
            field=models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.CreateModel(
            name='SectionRankStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.BigIntegerField(blank=True, null=True, verbose_name='디비 순위 (전체)')),
                ('ranking_rate', models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)(전체)')),
                ('section_ranking', models.FloatField(blank=True, null=True, verbose_name='디비 순위 백분위 (상위)(전체)')),
                ('estimate_ranking', models.BigIntegerField(blank=True, null=True, verbose_name='추정 순위 (플랫폼 전체 풀)(전체)')),
                ('estimate_ranking_rate', models.FloatField(blank=True, null=True, verbose_name='추정 순위 백분위(플랫폼 전체 풀)(전체)')),
                ('section_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.categorysection')),
                ('section_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.countrysection')),
                ('section_follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.followersection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='audiencequality',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='demographicsgender',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='demographicslanguages',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='featuringscore',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='reachscore',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='realinfluencescore',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
        migrations.AddField(
            model_name='trend',
            name='section_ranking',
            field=models.ManyToManyField(blank=True, to='report.SectionRankStatus'),
        ),
    ]
