# Generated by Django 3.2.6 on 2021-09-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20210914_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionrankstatus',
            name='section_ranking',
        ),
        migrations.RemoveField(
            model_name='termrankingaccount',
            name='section_ranking',
        ),
    ]
