# Generated by Django 3.2.6 on 2021-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20210914_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienceindicator',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='audiencequality',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='demographicsgender',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='demographicslanguages',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='featuringscore',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='reachscore',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='realinfluencescore',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='termrankingaccount',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.AddField(
            model_name='trend',
            name='section_ranking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 백분위 (상위)(전체)'),
        ),
        migrations.RemoveField(
            model_name='audienceindicator',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='audienceindicator',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='audiencequality',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='audiencequality',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='demographicsage',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='demographicsage',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='demographicsgender',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='demographicsgender',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='demographicslanguages',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='demographicslanguages',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='engagement',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='featuringscore',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='featuringscore',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='reachscore',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='reachscore',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='realinfluencescore',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='realinfluencescore',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='termrankingaccount',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='termrankingaccount',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.RemoveField(
            model_name='trend',
            name='section_ranking',
        ),
        migrations.AddField(
            model_name='trend',
            name='section_ranking',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='섹션(팔로워,카테고리,국가) 디비 순위 (전체)'),
        ),
        migrations.DeleteModel(
            name='SectionRankStatus',
        ),
    ]
