# Generated by Django 3.2.6 on 2021-09-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20210914_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrankstatus',
            name='section_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.platformsection'),
        ),
    ]
