# Generated by Django 3.2.6 on 2021-09-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20210914_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachscore',
            name='campaign_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='캠페인 예상 제휴 단가'),
        ),
        migrations.AddField(
            model_name='reachscore',
            name='reach_sales',
            field=models.IntegerField(blank=True, null=True, verbose_name='도달 예상 매출'),
        ),
    ]
