# Generated by Django 3.2.6 on 2021-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_auto_20210915_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reachscore',
            name='campaign_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='캠페인 예상 제휴 단가'),
        ),
        migrations.AlterField(
            model_name='reachscore',
            name='reach_sales',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='도달 예상 매출'),
        ),
    ]
