# Generated by Django 3.2.6 on 2021-10-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20211006_1053'),
        ('report', '0024_auto_20210915_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='iguserinfo',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userinfo', to='component.account'),
        ),
    ]
