# Generated by Django 3.2.6 on 2021-08-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('ig_pk', models.IntegerField()),
                ('yt_pk', models.IntegerField()),
                ('tk_pk', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=25)),
                ('categories', models.ManyToManyField(to='component.Category')),
            ],
        ),
        migrations.CreateModel(
            name='IgStatisticsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('estimate_age', models.FloatField(blank=True, null=True)),
                ('estimate_gender', models.FloatField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_brand', models.BooleanField(blank=True, null=True, verbose_name='브랜드')),
                ('is_celebrity', models.BooleanField(blank=True, null=True, verbose_name='유명인')),
                ('is_fake', models.BooleanField(blank=True, null=True)),
                ('is_bot', models.BooleanField(blank=True, null=True)),
                ('is_advertiser', models.BooleanField(blank=True, null=True)),
                ('is_not_reach', models.BooleanField(blank=True, null=True)),
                ('is_not_active', models.BooleanField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ig_profile_statistics', to='component.account')),
                ('tags', models.ManyToManyField(blank=True, to='component.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IgStatisticsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('estimate_age', models.FloatField(blank=True, null=True)),
                ('estimate_gender', models.FloatField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ig_content_statistics', to='component.account')),
                ('tags', models.ManyToManyField(blank=True, to='component.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IgAccountRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('is_follower', models.BooleanField(blank=True, null=True, verbose_name='팔로워 유무')),
                ('comment_count', models.IntegerField(blank=True, null=True, verbose_name='댓글 갯수')),
                ('like_count', models.IntegerField(blank=True, null=True, verbose_name='좋아요 갯수')),
                ('mention_count', models.IntegerField(blank=True, null=True, verbose_name='멘션 갯수')),
                ('tag_count', models.IntegerField(blank=True, null=True, verbose_name='태그 갯수')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='component.account', verbose_name='분석대상 계정')),
                ('rel_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.account', verbose_name='연관 계정')),
                ('tags', models.ManyToManyField(blank=True, to='component.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('tags', models.ManyToManyField(blank=True, to='component.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('ig_pk', models.IntegerField()),
                ('yt_pk', models.IntegerField()),
                ('tk_pk', models.IntegerField()),
                ('tags', models.ManyToManyField(blank=True, to='component.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, to='component.Tag'),
        ),
    ]
