# Generated by Django 3.2.6 on 2021-10-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='component.category'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('code', 'category')},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='categories',
        ),
    ]
