# Generated by Django 3.2.6 on 2021-10-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20211006_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ig_pk',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='tk_pk',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='yt_pk',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='ig_pk',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='tk_pk',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='yt_pk',
            field=models.BigIntegerField(),
        ),
    ]
