# Generated by Django 3.2.6 on 2021-10-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_auto_20211006_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='igstatisticscontent',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ig_content_statistics', to='component.content'),
        ),
    ]
