# Generated by Django 3.2.6 on 2021-10-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_igstatisticscontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igstatisticscontent',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_content_statistics', to='component.account'),
        ),
    ]
