# Generated by Django 3.2.6 on 2021-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0007_auto_20211006_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='igstatisticscontent',
            name='is_tag_classification',
            field=models.BooleanField(blank=True, default=False, verbose_name='태그 분류 유무'),
        ),
        migrations.AddField(
            model_name='igstatisticscontent',
            name='tag_classification_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='igstatisticsprofile',
            name='is_tag_classification',
            field=models.BooleanField(blank=True, default=False, verbose_name='태그 분류 유무'),
        ),
        migrations.AddField(
            model_name='igstatisticsprofile',
            name='tag_classification_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
