# Generated by Django 3.2.6 on 2021-10-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0009_auto_20211006_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='igstatisticscontent',
            name='palette_colors',
            field=models.JSONField(blank=True, help_text='[{hex:Char,r:Int,g:Int,b:Int}, ..]', null=True),
        ),
    ]
