from django.core.management import BaseCommand
from report.models.report import *
from instagram_score.models import Userinfo, Scorev1
import requests, traceback
import time
from statistics import fmean
from report.make_stat import make_status_ig_user, rank_ig_user
from component.views import classifier_user
class Command(BaseCommand):
    def handle(self, *args, **options):

        # input_users = IGUserInfo.objects.order_by('?').all().values_list('username', 'pk')
        
        # rank_users = []
        # for username, insta_pk in input_users:
        #     try:
        #         make_status_ig_user(username, insta_pk)
        #         rank_ig_user(insta_pk)
        #     except:
        #         print(traceback.format_exc())


        #Top 1000
        input_users = [
            # 'jennierubyjane',
            # 'bts.bighitofficial',
            # 'roses_are_rosie',
            # 'sooyaaa__',
            # 'blackpinkofficial',
            # 'adidas',
            # 'actorleeminho',
            # 'jacksonwang852g7',
            # 'eunwo.o_c',
            # 'oohsehun',
            # 'dlwlrma',
            # 'baekhyunee_exo',
            # 'xxxibgdrgn',
            # 'jongsuk0206',
            # 'twicetagram',
            # 'bn_sj2013',
            # 'jichangwook',
            # 'taeyeon_ss',
            # 'skuukzky',
            # 'hyunah_aa',
            # 'skawngur',
            # 'realstraykids',
            #### 'layzhang',
            # 'bighit_ent',
            # 'heybiblee',
            # 'zkdlin',
            # 'yoona__lim',
            ###'choi_seung_hyun_tttop',
            # 'smtown',
            # '_imyour_joy',
            # 'ssinz7',
            # '__youngbae__',
            # 'kyo1122',
            # 'nct127',
            # 'wow_kimsohyun',
            # 'soohyun_k216',
            # 'nct',
            # 'itzy.all.in.us',
            # 'taehyung.bighitentertainment',
            # 'marktuan',
            # 'leedongwook_official',
            # 'jungkook_bighitentertainment',
            # 'lucas_xx444',
            # 'hi_high_hiy',
            # 'yu_gyeom',
            # 'redvelvet.smtown',
            # 'tiffanyyoungofficial',
            # 'hi_sseulgi',
            # 'jimin_bighitentertainment',
            # 'somsomi0309',
            # 'songkang_b',
            # 'jessica.syj',
            # 'vousmevoyez',
            # 'koreadispatch',
            # 'daraxxi',
            # 'kimjuncotton',
            # 'jin_bighitentertainment',
            # 'txt_bighit',
            # 'jhope_bighitentertainment',
            # 'rm_bighitentertainment',
            # 'mejiwoo103',
            # 'suga_bighitentertainment',
            # 'chaelincl',
            # 'jinyoung_0922jy',
            # 'rachel_mypark',
            # '_jeongjaehyun',
            # 'bts.jungkook',
            # 'bumkeyk',
            # 'yerimiese',
            # 'henryl89',
            # 'renebaebae',
            # 'tenlee_1001',
            # 'saythename_17',
            # 'siwonchoi',
            # 'seungriseyo',
            # 'do0_nct',
            # 'jessicah_o',
            # 'btsjimin',
            # 'e_xiu_o',
            # 'nct_dream',
            # 'bts.world.official',
            # 'ponysmakeup',
            # 'bts.world.official',
            # 'miyayeah',
            # 'got7.with.igot7',
            # 'btstae',
            # 'm_kayoung',
            # 'mamamoo_official',
            # 'na.jaemin0813',
            # 'phs1116',
            # '_mariahwasa',
            # 'seojuhyun_s',
            # 'johnnyjsuh',
            # 'leedonghae',
            # 'official_g_i_dle',
            # 'geewonii',
            # 'jelly_jilli',
            # 'onyourm__ark',
            # 'jin.bts',
            # 'bts_v',
            # 'sooyoungchoi',
            # 'bts_jhope',
            # 'taeoxo_nct',
            # 'jaybnow.hr',
            # 'hyeri_0609',
            # 'realllllmino',
            # 'yesung1106',
            # 'bt21_official',
            # 'official_monsta_x',
            # 'btsnamjoon',
            # 'actor_jg',
            # 'yulyulk',
            # 'hyoyeon_x_x',
            # 'wwiinn_7',
            # 'kimheenim',
            # 'seonho__kim',
            # 'jparkitrighthere',
            # 'lm_____ltm',
            # 'superm',
            # 'yangyang_x2',
            # 'chungha_official',
            # 'actor_jisoo',
            # 'holyhaein',
            # 'hm_son7',
            # 'xxteukxx',
            # 'aespa_official',
            # 'ateez_official_',
            # '515sunnyday',
            # 'todayis_wendy',
            # 'you_r_love',
            # 'yejinhand',
            # 'xeesoxee',
            # 'min9yu_k',
            # 'masijacoke850714',
            # 'shinee',
            # 'woozico0914',
            # 'ahnhani_92',
            # 'ldh_sky',
            # 'daniel.k.here',
            # 'ggonekim',
            # 'mo_onbyul',
            # 'wonhari',
            # 'deejaysoda',
            # 'wdohwan',
            # 'jimin',
            # 'bts0fficial',
            # 'officialastro',
            # 'jypentertainment',
            # 'yeojin9oo',
            # 'k.kbeom',
            # 'seokj1012',
            # 'official_lai_kuanlin',
            # 'btssuga',
            # 'bts.suga',
            # 'yg_treasure_official',
            # 'withikonic',
            # 'xuminghao_o',
            # 'youngdae0302',
            # 'yellow_3to3',
            # 'shxxbi131',
            # 'hyojong_1994',
            # 'leeseunggi.official',
            # 'jiyeon2__',
            # '0529.jihoon.ig',
            # 'ewsbdi',
            # 'quanhaha79',
            # 'kjk76',
            # 'ericnam',
            # 'optimushwang',
            # 'osw_onge',
            # 'boakwon',
            # 'my_songjihyo',
            # 'borabora_sugar',
            'yook_can_do_it',
            'ryusdb',
            'minah320_97',
            'jxxvvxxk',
            'gfriendofficial',
            'youna_1997',
            'juanxkui',
            'hellopapa11',
            'sh_9513',
            'official_kard',
            'bobbyindaeyo',
            'joshu_acoustic',
            'leehi_hi',
            'wannaone.official',
            'aagbanjh',
            'imhyoseop',
            'kim_msl',
            'marcellasne_',
            'juneeeeeeya',
            'pledis_boos',
            'kwakdongyeon0',
            '_minzy_mz',
            'jin_a_nana',
            'chwenotchew',
            'clean_0828',
            'seo_cccc',
            'tvndrama.official',
            'arden_cho',
            'ron_sae',
            'sjkuksee',
            'jilwww',
            'mr_kanggun',
            'mo.on_air',
            'xhyolynx',
            'moon_ko_ng',
            'hye_yoon1110',
            '1004yul_i',
            'gnani_____',
            'rain_oppa',
            'dlstmxkakwldrl',
            'bts.bighit.__',
            'leejungshin91',
            'y_haa.n',
            'w_n_r00',
            'leesiyoung38',
            'ddana_yoon',
            'chang._.a',
            'blobyblo',
            'bigmatthewww',
            'callmegray',
            'bighit7official',
            'akmu_suhyun',
            'hyominnn',
            'ohvely22',
            'zennyrt',
            'woozi_universefactory',
            'minhyuk202523',
            'rovvxhyo',
            'sbs_runningman_sbs',
            'sound_of_coups',
            'jungkookbts',
            'jungkook_forever',
            'inkyung97',
            'leesoohyuk',
            'earlyboysd',
            'official_everglow',
            'shinhs831',
            'jyheffect0622',
            'smtownandstore',
            'songilkook',
            'sssong_yh',
            'official_theboyz',
            'voguekorea',
            'jeeseokjin',
            'i_icaruswalks',
            'actor_jingoo',
            'chan_w000',
            'day6kilogram',
            'choiminho_1209',
            'momoland_official',
            'netflixkr',
            'soooo_you',
            'elina_4_22',
            'crush9244',
            '____kimwoobin',
            'cube_ptg',
            'ireneisgood',
            'ast_jinjin',
            '_dong_ii',
            'd_a___m_i',
            'han_ye_seul_',
            'illusomina',
            'overdokyungsoo',
            'artist_eunji',
            'mj_7.7.7',
            'ncit_kimjw',
            'skullhong12',
            'blackpinkcofficial',
            'samuliesword',
            'hihyunwoo',
            'solarkeem',
            'newharoobompark',
            'kumajaewoo',
            'bts__jungk00k',
            'sambahong',
            'whee_inthemood',
            'hanjiji54',
            'hongsick',
            'j_chaeyeoni',
            'hyorin_min',
            'somin_jeon0822',
            'loonatheworld',
            'heizeheize',
            'iammingki',
            '_zziwooo0',
            'marieclairekorea',
            'yunho2154',
            'taecyeonokay',
            'betterlee_0824',
            'bts.0fficials',
            'goyounjung',
            'ellekorea',
            'kookoo900',
            'awesomehaeun',
            'dntlrdl',
            'e.jiah',
            'dahee0315',
            're_mini_scene',
            'jaehwan0527',
            'satgotloco',
            'maetamong',
            'jj_1986_jj',
            'yg_ent_official',
            'ziont',
            'real.be',
            'hyunjoong860606',
            'yoo_yeonseok',
            'kim_d.he',
            'hjonghyun',
            'candyseul',
            'deantrbl',
            'gyuram88',
            'wooju1025',
            'yura_936',
            '_yoonj1sung_',
            'changmin88',
            'taeri__taeri',
            'jinyoung0423',
            '2km2km',
            'imjennim',
            'k_hanna_',
            'nancyjewel_mcdonie_',
            'cxxsomi',
            'j.seph_',
            'kimyk10',
            'gooreumseng',
            '__shinyeeun',
            'somin_jj',
            'le2jh',
            'xxjjjwww',
            'longlivesmdc',
            'official_jimiin',
            'ravithecrackkidz',
            'sunghoon1983',
            'tabloisdad',
            'eugene810303',
            'sodam_park_0908',
            'hutazone',
            'kimminkyu_0312',
            'hanhyojoo222',
            'labels.hybe',
            'eajpark',
            'jiminxjamie',
            'ab6ix_official',
            'bohyunahn',
            'official_oneus',
            '42psy42',
            'winnercity',
            'koohara__',
            'hermosavidaluna',
            'williamhammington',
            'chengxiao_0715',
            'meow91__',
            'sonsungdeuk',
            'dj_gpark',
            'bts.7',
            'achahakyeon',
            'aileeonline',
            'honey_lee32',
            'kbsdrama',
            'susemee',
            'stylenanda_korea',
            'komurola',
            'sysysy1102',
            'for_everyoung10',
            'melovemealot',
            'inhyuk_bb',
            'parkb0gum',
            'nwh91',
            'w_o_o_y_a',
            '3.48kg',
            'jinmiran_',
            'woo.ddadda',
            'lavieenbluu',
            'woodz_dnwm',
            'soominn_jo',
            'b__yccn',
            'dk_is_dokyeom',
            'produce_x_101',
            'btsjungk00kie',
            'justin_jisung',
            'zzyuridayo',
            'khunsta0624',
            'yooranna',
            '0myoung_0526',
            'yoanaloves',
            'akmuchanhk',
            '_____silverstone_____',
            'cookat_korea',
            'parkhaejin_official',
            'lafilledhiver_',
            'imnameim',
            'dlehdgnl',
            'kanginnim',
            'yute_v',
            'wm_ohmygirl',
            'bentleyhammington',
            'kimwon.pil',
            'kasper0524',
            'yubi_190',
            'aksakfn12',
            'glorypath',
            'boyoung0212_official',
            'taeuniverse',
            'yookihhh',
            'nayoungkeem',
            'dbqudwo333',
            'yuqisong.923',
            'bbang_93',
            'roma.emo',
            'jeonghaniyoo_n',
            'mrs_macarons',
            'actorctj',
            'kim_bora95',
            'pyojihoon_official',
            'mingi_1122',
            'todayhouse',
            'soobinms',
            'ye._.vely618',
            'every__nn',
            'from_youngk',
            'hyukoh2000',
            'kyj._.95',
            'jeonghwa_0508',
            'ara_go_0211',
            'blackpinks',
            'jeonjungkook__bts',
            'cix.official',
            'yysbeast',
            'souththth',
            'jsomin86',
            'everyone_woo',
            'holly608',
            'jeon.yeobeen',
            'min.nicha',
            '2xj_hee',
            'pockyjr',
            'rlo.ldl',
            'youngji_02',
            'hv_nara',
            'kwon_jo',
            'hyuniiiiiii_95917',
            'yoonjujang',
            'minn.__.ju',
            'sangyeob',
            'ddablue',
            'd.ddablue',
            'girlsgeneration',
            'gominsi',
            'nuest_official',
            'doflwl',
            'chaileeson',
            'travelholic_insta',
            'leo_jungtw',
            'yu.n_wk',
            'hyemhyemu',
            'moonjaein',
            'eden_table',
            'btobpeniel',
            'boram__jj',
            'gojoonhee',
            'vely.mom',
            'xodambi',
            '_yujin_an',
            '_happiness_o',
            'pyoapple',
            'ummmmm_j.i',
            'onedayxne',
            'min_namkoong',
            'cravity_official',
            'soul.g_heo',
            'official.apink2011',
            'jstar_allallj',
            'sunbin_eyesmag',
            'official_a.c.e7',
            'mcnd_official',
            'prince_kwanghee',
            'etudeofficial',
            'kkachi99',
            'mjbaby0203',
            's911010',
            'bscenez',
            'bitnara1105',
            'bts.0fficail',
            'exidofficial',
            'sora_pppp',
            'hyeliniseo',
            'kimdwan_',
            'aomgofficial',
            'songseungheon1005',
            'btob_silver_light',
            'hwa.min',
            '_______youngmoney',
            'cube_clc_official',
            'smtownstation',
            'jungkookjeon7',
            'liakimhappy',
            'gookju',
            'mingue.k',
            'ljh_babysun',
            '10000recipe',
            'xxadoraa',
            'mulgokizary',
            'dprlive',
            'vixx_stargram',
            'ho5hi_kwon',
            'jtbcdrama',
            'haneulina',
            'yuuzth',
            'som0506',
            'real_jinhyuk',
            'kjh_official',
            'x_xellybabyx',
            'yim_siwang',
            'wjsn_cosmic',
            'deukie_______',
            'bk_arta',
            'kanggary_yangban',
            'moonjungwon',
            'hyun.jxx0_p',
            'modelhanhyejin',
            'giriboy91',
            'vliveofficial',
            'dok2gonzo',
            'jangsk83',
            'noodle.zip',
            'madongseok_',
            'ff0427',
            'dispatch_style',
            'holland_vvv',
            'demi_kimee',
            'jaeuck.kim',
            'yeh.shaa_',
            'reveramess_',
            '_ohhayoung_',
            'risabae_art',
            'officialfromis_9',
            'ryuniverse328',
            'realisshoman',
            'jrjswn',
            'jihye8024',
            'ohttomom',
            'chaestival_',
            'silver_rain.__',
            'jungeum84',
            'kopular',
            'lee_cs_btob',
            'taehyuntxt_official',
            'park_yury',
            'tiny.pretty.j',
            'tiny.pretty.j',
            '_chaechae_1',
            '__yoonbomi__',
            'shownuayo',
            'ysh6834',
            'vtcosmetics_official',
            'lee_si_eon',
            'imhyunsik',
            'wanna._b',
            'hazzisss',
            'c_chani_i',
            'hongsuzu',
            'soobin1119',
            'dbeoddl__',
            'woooojin0408',
            'yujin_so',
            'innisfreeofficial',
            'leejehoon_official',
            'beatburgerjae',
            'greedeat',
            'iu_leejieun516',
            'yena.jigumina',
            'doonabae',
            'shinee_jp_official',
            'henn_kim',
            'baebaealice',
            'don9_han',
            'chaejh_',
            'sbsnow_insta',
            'bts.jungkookt',
            'jinjoo1224',
            'ggumigi',
            'eunjung.hahm',
            'y.na__',
            'jeee622',
            'kimbutter_daddy',
            'taeyang_0228',
            'kisy0729',
            'yoo__sha',
            'kookies_luv',
            '216jung',
            'bts.bang1an',
            'tobenstagram',
            'sarangdungy',
            'leeminho_mino',
            'bemy_rin',
            'changmo_',
            'socun89',
            '2ah.in',
            '_weeekly',
            'beautyplmagazine',
            'type4graphic',
            'knhs2',
            'slowswan',
            'kangmeen',
            'ph1boyyy',
            'sejinming',
            'manyo_yoojin',
            'gu9udan',
            '0seungyeon',
            'byzelo',
            'mayj517',
            'gentlemonster',
            'kkmmmkk',
            'bangstergram',
            'ophen28',
            '1995.mj',
            'mbcdrama_now',
            'bts',
            'nuestaron',
            'tae_rii_',
            'jungkookjeon',
            's_sohye',
            'ch_amii',
            'zo__glasss',
            'insight.co.kr',
            'jane.asmr',
            'jfla',
            'official_sunmi',
            'yebin__',
            'official_jdh',
            'jang.doyoun',
            'khxxn_',
            'woohye0n',
            'coenffl',
            'luvlk89',
            'junha0465',
            'tvxq.official',
            'ssozi_sojin',
            'chosaeho',
            'billboard_korea',
            'yerin_the_genuine',
            'bewhy.meshasoulja',
            'official_therose',
            'hyun_woo_tv',
            '__leeheeeun__',
            'han_kyung__',
            'gini_s2_',
            'young_g_hur',
            'kevinwoo_official',
            'nail_unistella',
            'yangse2848',
            'thequiett',
            'vivamoon',
            'jimincut',
            'official.hasungwoon',
            'nakedbibi',
            'danielhenney',
            'yoonjongactor_official',
            'hhy6588',
            'shinhancard_official',
            'namdareum_mom',
            'jungdabiny',
            'seojin_ban',
            'dei8ht',
            'stephanielee199',
            'bn_95819',
            'bn_95819',
            'mixxmix_seoul',
            'zipcy',
            'cs__min',
            '4000man_',
            'leetaehwan0221',
            'leetaehwan0221',
            '_choiiii__',
            'yj_loves',
            'weki_meki',
            'djjina_official',
            'kim.tae95bts',
            'got7updates_',
            'estapramanita',
            'ulael_',
            'yunakim',
            'zzangjeolmi',
            'fila_korea',
            '_angel_elijah_',
            'rh_ab',
            'lilyiu_',
            'gyeongree',
            'therealminnn',
            'gyeongree',
            'kbsworldtv',
            'nam_yoonsu',
            'imvely_jihyun',
            'code_kunst',
            'kieunse',
            'ssoheean',
            'bts.taehyung',
            '_taeyeonfanpage',
            'seungwon_jeong',
            '0__0man',
            'hanna91914',
            'lovelyjoohee',
            'dj_siena',
            'jun._.0512',
            'superstar_jhs',
            'tvn_joy',
            'candyz_hyojung',
            'jypactors_official',
            'younghotyellow94',
            'dindinem',
            'tojws',
            'munchinthepool',
            '_kimjaekyung_',
            'kongkong2_kim',
            'dengdeng_e',
            'subinyu1106',
            'ssoyang84',
            'samhammington',
            'naturerepublic_kr',
            '_minjukim_',
            'suminzz',
            'dxhxnxe',
            'qtfreet',
            'exo',
            'lovely.katie.k',
            'kto940620',
            'keykney',
            'woo_o9o',
            'yoon_ambush',
            'kkamooong',
            'cube_official_btob',
            '1993kg',
            'cherrybullet',
            'designdain',
            'tangle_mimi',
            'thebangtanboy.bts',
            'emartstore',
            'ttokkii',
            'jiyeon.s_0',
            'bts_0fficail',
            '10042n00',
            'ssaaaann__22',
            'kkwonsso_94',
            'yg_kplus',
            'banyoonhee',
            'sola5532',
            'chloelxxlxx',
            'dongdong810',
            'sooviin38',
            'seola_s',
            'bimil_jieun',
            'godjp',
            'lloveeely',
            'taekook.tv',
            'l_hajoon',
            'super_d.j',
            'super_d.j',
            'soltattoo',
            'for_gomroni_',
            '_____jjh',
            'clorlk',
            'hyunheehong',
            'ash.island',
            'thousand_wooo',
            'the_verivery',
            '_liustudio_',
            'byeonwooseok',
            'd.of.j.c',
            'park_bosung',
            'uyj__0803',
            'sunmiub',
            'jung.y00n',
            'kaijexo',
            'kimehwa',
            'bh_bts7',
            'rkm0855',
            'yyyyeeun',
            'chulsoon_official',
            'ssss3063',
            'kimheebibi',
            'supermom_sujin',
            'r_yuhyeju',
            'official_gncd11',
            'leejongsuky',
            'seonkyounglongest',
            'taevin.lee',
            'amourfor_u',
            'jungnam_bae',
            'lee____bora',
            'innisfree.instalog',
            'j_oo.e_0en',
            'se7enofficial',
            'h1ghrmusic',
            'itsjustswings',
            'yjiinp',
            '__chommy',
            'eeunseo._.v',
            'melodysoyani',
            'do.hyeon_im',
            'oneroom.make',
            'mgain83',
            '_seong_hee',
            'choehyeokgeun',
            'got7_fanclub',
            'joohoneywalker',
            'hyo_joo',
            'oxxooi',
            'syv0428',
            'superb_ean',
            'fashionandstyle.official',
            'hunter.kang',
            'shin_sung_rok',
            'garin_ss',
            'damikwon_',
            'yoonhyunmin',
            'dglee20',
            'official_yooseonho',
            'lsod.d',
            'yjaybaby',
            'jupppal',
            'sung_yuri_',
            'jess.02.23',
            'junghyesung91',
            'chanmi_96a',
            'dlgofl85',
            'peripera_official',
            'bangtanparkjimin',
            'cindynoona',
            'cu_official',
            'chuu_official',
            'exy_s2',
            'eatmother',
            'grim_b',
            'hello_dongwon',
            'babebani',
            'saico0111',
            'kjjzz87',
            'h1003141592',
            'ukiss_jun97',
            'seyoung_10',
            '_asia_prince_jks',
            'clio_official',
            'daxbin',
            'dasom_lovely',
            'hsh0705',
            'heeae_official',
            'zihwa_tattooer',
            'real_2pmstagram',
            'lalalalisa_ma',
            'z_hera',
            '92_hyungseok',
            'mlnhe',
            'tt_trend',
            'playlist_studio',
            'wonlog',
            'braveg_yj',
            '94_j.a',
            'minyoung_aori',
            'jinwoon52',
            'giantpengsoo',
            'chaelisa.area',
            'leanavvab',
            'bts7_txt',
            'kidcozyboy',
            'yjoo_oh',
            'pigmong___',
            'r0s8y_',
            'oddhw',
            'ggulhouse',
            'moonjongyeup',
            '_maoi_yua_hyun_',
            'mayersung',
            'oliveyoung_official',
            'btsjungkooki_',
            'sungcheol2',
            'baroganatanatda',
            'k_jenny_k',
            'ahoi_ing',
            'chungjizzle',
            'foodyinkorea',
            'aahnjaehong',
            'yoojunglee11',
            'jiyoon_park_',
            'saegeemtattoo',
            'nana.un',
            'nayoung_lim95',
            'ssovely1024',
            'sungziyoung',
            'euddeume_',
            'noahmik',
            'leechungah',
            'theeasychan',
            'midorithais',
            'hyesuuuuuya',
            'pkalbum',
            'a12486',
            'joowon.unnie',
            'ayeoniiiiii',
            'hajunn_mom',
            'thesy88',
            'han_bling_',
            'highcutstar',
            'cog.j_92',
            'ch.yoooon',
            'jihoa_f',
            'yn_s_1230',
            'jinkyung3_3',
            'xiaxiaxia1215',
            'n.d.kim',
            'cook_and_candle',
            'gunheenim',
            '7elevenkorea',
            'luv__ribbon',
            'hyunbeenshin',
            'englishforkorean',
            'yoonara_mood',
            'tv_blackpink',
            'lisablackspink',
            'callmenahna',
            '___solvely___',
            'ttovely__',
            'lee_mido',
            'hehehe0',
            'jeong.woo.joo',
            'wg_lim',
            'kisum0120',
            'j_10.2_76',
            'woooozzzzz',
            'officialc9ent',
            'ioi_official_ig',
            'frombeginning_',
            'cheap_box',
            'jye._.e',
            'xxjominxx',
            'koreanenglishman',
            'haseokjin',
            'boori_boo',
            'official_lvlz8_',
            'seon_uoo',
            'mido_ring',
            'faker',
            '131moon_',
            'dear.zia',
            'hatfelt',
            'dayomi99',
            'jtbc.insta',
            'nizinanjjang',
            'yoonmida',
            'khmnim1513',
            'soonmoo_cat',
            '8eomatom',
            'ivenoven',
            '2__yun__2',
            'btsjungkook.97',
            '_eunz1nara_',
            'ssung916',
            'graziakorea',
            'converse_kr',
            'on_do__',
            'yeonions',
            'subsubey',
            'bts._.7boys',
            'jaelim_song',
            'im_hyeonzzu',
            'hazelnut_dog',
            'moonheeyul',
            'soojunglim_',
            'pinkgabong',
            'lalisa_blackpinks',
            'bts.igs',
            'smitruti1010',
            'soribaby',
            'yoou.ch',
            'laneige_kr',
            'my.o_',
            'dasolmom_',
            'queenchoa_',
            'originals_kr',
            'krunk_official',
            'iluvyub',
            'phh1013',
            'vminkook_tv',
            'sonhojun_officia',
            'hashblanccoa',
            'ohseunghee_official_',
            'hyexok_',
            'ue1124',
            'lesleyhee',
            'sanethebigboy',
            'seungwoolee',
        ]


        
        
        while True:
            report = Reportv1.objects.order_by('?').first()
            username = None
            try:
                username = report.userinfo.username
            except:
                continue

            if username == None:
                continue

            try:
                if IGUserInfo.objects.filter(username=username).exists():
                    continue


                print(f'{username} - Start')
                res = requests.get(f'https://feat.report/crawl_instagram_save?request_type=user&parameter={username}')
                time.sleep(5)
                make_status_ig_user(username)
                ig_userinfo = IGUserInfo.objects.get(username=username)
                rank_ig_user(ig_userinfo.pk)
                classifier_user(username)

            except:
                print("ERROR ------- ", username)